/* Programme detail content. Every string is { en, fr }. Facts (durations, group sizes, formats) come from the original programme cards;
   modules and outcomes are draft descriptions for Windsor to confirm. */
(function () {
  function b(en, fr) { return { en: en, fr: fr }; }
  function f(k, v) { return { k: k, v: v }; }
  var P = [
    { id: 'corporate', icon: 'fa-building', name: b('Windsor Corporate Programme', 'Programme Windsor Corporate'), tag: b('Flagship · groups of 8 to 12', 'Programme phare · groupes de 8 à 12'),
      intro: b('A hybrid course that takes a whole team from where they are to confident, everyday Business English, using the emails, meetings and calls of their own workplace.', 'Un cours hybride qui fait progresser toute une équipe vers un Business English assuré au quotidien, à partir des e-mails, réunions et appels de son propre travail.'),
      who: [b('Managers and employees whose work already involves English', 'Cadres et employés dont le travail implique déjà l’anglais'), b('HR and training managers who need a structured, measurable course', 'Responsables RH et formation qui veulent un cours structuré et mesurable')],
      outcomes: [b('Write clear, professional emails and short reports', 'Rédiger des e-mails et de courts rapports clairs et professionnels'), b('Take part in meetings and calls with confidence', 'Participer aux réunions et appels avec assurance'), b('Move up at least one visible step on the CEFR scale', 'Progresser d’au moins un niveau visible sur l’échelle du CECRL')],
      modules: [b('Workplace emails and messages', 'E-mails et messages professionnels'), b('Meetings, calls and small talk', 'Réunions, appels et conversation informelle'), b('Presenting updates and figures', 'Présenter des points d’étape et des chiffres'), b('Grammar in context, learned by discovery', 'Grammaire en contexte, apprise par découverte')],
      facts: [f(b('Length', 'Durée'), b('20 h or 40 h formats', 'Formats de 20 h ou 40 h')), f(b('Group size', 'Taille du groupe'), b('8 to 12 learners', '8 à 12 apprenants')), f(b('Delivery', 'Format'), b('Face to face, Zoom and LMS', 'Présentiel, Zoom et LMS'))],
      inc: [b('Windsor LMS access', 'Accès au LMS Windsor'), b('CEFR-aligned curriculum', 'Programme aligné sur le CECRL'), b('Practice with Windsor', 'Pratique avec Windsor')] },
    { id: 'executive', icon: 'fa-user-tie', name: b('Executive English Coaching', 'Coaching d’anglais pour dirigeants'), tag: b('One-to-one · 10, 20 or 30 sessions', 'Individuel · 10, 20 ou 30 séances'),
      intro: b('Private coaching built around your calendar, your industry and the situations that matter most to you, from board updates to negotiations abroad.', 'Un coaching privé construit autour de votre agenda, de votre secteur et des situations qui comptent le plus, des comptes rendus au conseil aux négociations à l’étranger.'),
      who: [b('C-level executives, directors and HR directors', 'Dirigeants, directeurs et DRH'), b('Senior managers preparing for international roles', 'Cadres supérieurs qui préparent un rôle international')],
      outcomes: [b('Lead meetings and present with authority', 'Diriger des réunions et présenter avec autorité'), b('Negotiate and handle difficult questions calmly', 'Négocier et répondre aux questions difficiles avec calme'), b('Speak and write with the tone your role requires', 'Parler et écrire avec le ton que votre rôle exige')],
      modules: [b('Needs analysis and personal goals', 'Analyse des besoins et objectifs personnels'), b('Negotiation and persuasion', 'Négociation et persuasion'), b('Executive presentations with the PREP method', 'Présentations de dirigeant avec la méthode PREP'), b('Written communication at senior level', 'Communication écrite de haut niveau')],
      facts: [f(b('Sessions', 'Séances'), b('10, 20 or 30', '10, 20 ou 30')), f(b('Format', 'Format'), b('One-to-one, flexible hours', 'Individuel, horaires flexibles')), f(b('Coach', 'Coach'), b('Experienced with executives', 'Expérimenté auprès des dirigeants'))],
      inc: [b('Tailored content from your industry', 'Contenus de votre secteur'), b('Progress notes after sessions', 'Notes de progression après les séances'), b('Between-session practice with Windsor', 'Pratique entre les séances avec Windsor')] },
    { id: 'certs', icon: 'fa-certificate', name: b('International certifications', 'Certifications internationales'), tag: b('30 hours · TOEIC, TOEFL, BULATS, BEC', '30 heures · TOEIC, TOEFL, BULATS, BEC'),
      intro: b('Intensive preparation that teaches the exam format and the English behind it, so your score reflects your real ability.', 'Une préparation intensive qui enseigne le format de l’examen et l’anglais qui le sous-tend, pour que votre score reflète votre vrai niveau.'),
      who: [b('Professionals who need a score for a job, promotion or scholarship', 'Professionnels qui ont besoin d’un score pour un emploi, une promotion ou une bourse'), b('Candidates who want to prove their level to employers', 'Candidats qui veulent prouver leur niveau aux employeurs')],
      outcomes: [b('Know exactly what each exam tests and how it is marked', 'Savoir précisément ce que chaque examen évalue et comment il est noté'), b('Manage your time under exam conditions', 'Gérer votre temps en conditions d’examen'), b('Raise your score with targeted practice', 'Améliorer votre score grâce à une pratique ciblée')],
      modules: [b('Listening and reading strategies', 'Stratégies d’écoute et de lecture'), b('Speaking and writing tasks', 'Épreuves orales et écrites'), b('Vocabulary and grammar for exams', 'Vocabulaire et grammaire pour les examens'), b('Full mock tests with feedback', 'Examens blancs complets avec retour')],
      facts: [f(b('Length', 'Durée'), b('30 hours', '30 heures')), f(b('Exams', 'Examens'), b('TOEIC, TOEFL iBT, BULATS, Cambridge BEC', 'TOEIC, TOEFL iBT, BULATS, Cambridge BEC')), f(b('Mock tests', 'Examens blancs'), b('Included', 'Inclus'))],
      inc: [b('Study materials', 'Supports de cours'), b('Mock tests', 'Examens blancs'), b('Personal score feedback', 'Retour personnalisé sur votre score')] },
    { id: 'workshops', icon: 'fa-bolt', name: b('Windsor Workshops', 'Ateliers Windsor'), tag: b('One day · 7 hours · 5 modules', 'Une journée · 7 heures · 5 modules'),
      intro: b('Pick one skill, spend a day on it and leave with phrases and habits you can use at work the next morning.', 'Choisissez une compétence, consacrez-lui une journée et repartez avec des expressions et des réflexes utilisables dès le lendemain au travail.'),
      who: [b('Professionals who need to improve one skill fast', 'Professionnels qui doivent progresser vite sur une compétence'), b('Teams preparing for a specific event, such as a negotiation or pitch', 'Équipes qui préparent un événement précis, comme une négociation ou un pitch')],
      outcomes: [b('Apply new language in realistic practice tasks', 'Appliquer le nouveau langage dans des exercices réalistes'), b('Leave with a personal phrase bank', 'Repartir avec votre propre banque d’expressions'), b('Receive a certificate of completion', 'Recevoir une attestation de participation')],
      modules: [b('WW-01 Business Negotiation', 'WW-01 Négociation commerciale'), b('WW-02 High-Impact Presentations', 'WW-02 Présentations percutantes'), b('WW-03 Professional Writing', 'WW-03 Rédaction professionnelle'), b('WW-04 Meetings and Conference Calls', 'WW-04 Réunions et conférences téléphoniques'), b('WW-05 LinkedIn Optimisation', 'WW-05 Optimisation LinkedIn')],
      facts: [f(b('Length', 'Durée'), b('7 hours per workshop', '7 heures par atelier')), f(b('Modules', 'Modules'), b('5 to choose from', '5 au choix')), f(b('Proof', 'Preuve'), b('Certificate of completion', 'Attestation de participation'))],
      inc: [b('Workshop materials', 'Supports d’atelier'), b('Immediate application tasks', 'Exercices d’application immédiate'), b('Certificate of completion', 'Attestation de participation')] },
    { id: 'startups', icon: 'fa-rocket', name: b('English for Startups', 'Anglais pour startups'), tag: b('8-week cohort · 4 hours a week', 'Cohorte de 8 semaines · 4 h par semaine'),
      intro: b('A cohort for founders who want to pitch, answer investor questions and network internationally in clear, confident English.', 'Une cohorte pour entrepreneurs qui veulent pitcher, répondre aux investisseurs et réseauter à l’international dans un anglais clair et assuré.'),
      who: [b('Founders and co-founders preparing to raise funds', 'Fondateurs et cofondateurs qui préparent une levée de fonds'), b('Early teams selling to international customers', 'Équipes naissantes qui vendent à des clients internationaux')],
      outcomes: [b('Deliver a pitch with a clear story and structure', 'Présenter un pitch avec une histoire et une structure claires'), b('Answer investor questions without freezing', 'Répondre aux questions des investisseurs sans se bloquer'), b('Introduce yourself and your company at any event', 'Vous présenter, vous et votre entreprise, dans n’importe quel événement')],
      modules: [b('Your founder story and elevator pitch', 'Votre histoire de fondateur et votre elevator pitch'), b('Pitch deck language', 'Le langage du pitch deck'), b('Investor Q&A practice', 'Entraînement aux questions des investisseurs'), b('Networking and follow-up emails', 'Réseautage et e-mails de suivi')],
      facts: [f(b('Length', 'Durée'), b('8 weeks', '8 semaines')), f(b('Weekly time', 'Rythme'), b('4 hours a week', '4 h par semaine')), f(b('Format', 'Format'), b('Cohort with pitch practice', 'Cohorte avec entraînement au pitch'))],
      inc: [b('Pitch deck practice', 'Entraînement au pitch deck'), b('Investor English', 'Anglais pour investisseurs'), b('Cohort community', 'Communauté de cohorte')] },
    { id: 'b2b', icon: 'fa-handshake', name: b('B2B Corporate Solutions', 'Solutions entreprises B2B'), tag: b('In-company · teams of 10', 'En entreprise · équipes de 10'),
      intro: b('Training designed around your company: we audit your team, build content from your documents and report progress every month.', 'Une formation conçue autour de votre entreprise : nous auditons votre équipe, construisons les contenus à partir de vos documents et rendons compte chaque mois.'),
      who: [b('HR and L&D leaders training a department or branch', 'Responsables RH et formation qui forment un service ou une agence'), b('Companies with international clients, partners or head offices', 'Entreprises avec des clients, partenaires ou sièges à l’international')],
      outcomes: [b('See each learner’s starting CEFR level and target', 'Connaître le niveau CECRL de départ et l’objectif de chaque apprenant'), b('Train on your real emails, contracts and meetings', 'Se former sur vos vrais e-mails, contrats et réunions'), b('Show leadership clear monthly progress', 'Présenter à la direction une progression mensuelle claire')],
      modules: [b('Free language audit', 'Audit linguistique gratuit'), b('Custom content from your sector', 'Contenus sur mesure de votre secteur'), b('Live coaching on site or online', 'Coaching en direct sur site ou en ligne'), b('Monthly HR progress report', 'Rapport mensuel de progression pour les RH')],
      facts: [f(b('Team size', 'Taille de l’équipe'), b('10 people per module', '10 personnes par module')), f(b('Audit', 'Audit'), b('Free', 'Gratuit')), f(b('Reporting', 'Reporting'), b('Monthly', 'Mensuel'))],
      inc: [b('Free language audit', 'Audit linguistique gratuit'), b('Custom content', 'Contenus sur mesure'), b('HR progress reports', 'Rapports de progression RH')] },
    { id: 'lms', icon: 'fa-laptop', name: b('Windsor LMS', 'LMS Windsor'), tag: b('Included in every programme', 'Inclus dans tous les programmes'),
      intro: b('Our learning platform keeps practice going between lessons, with guided paths, instant feedback and a clear view of your progress.', 'Notre plateforme d’apprentissage prolonge la pratique entre les cours, avec des parcours guidés, un retour immédiat et une vue claire de votre progression.'),
      who: [b('Every Windsor learner, from the first day', 'Tous les apprenants Windsor, dès le premier jour'), b('Managers who want to see their team’s activity', 'Responsables qui veulent suivre l’activité de leur équipe')],
      outcomes: [b('Practise a little every day, on any device', 'Pratiquer un peu chaque jour, sur n’importe quel appareil'), b('Get recommendations that follow how you learn', 'Recevoir des recommandations qui suivent votre façon d’apprendre'), b('Track your progress toward your CEFR target', 'Suivre votre progression vers votre objectif CECRL')],
      modules: [b('Guided learning paths', 'Parcours d’apprentissage guidés'), b('Quick exercises with instant feedback', 'Exercices rapides avec retour immédiat'), b('Windsor, the AI tutor', 'Windsor, le tuteur IA'), b('Progress tracking', 'Suivi de progression')],
      facts: [f(b('Access', 'Accès'), b('Included with every programme', 'Inclus avec chaque programme')), f(b('Devices', 'Appareils'), b('Phone, tablet or computer', 'Téléphone, tablette ou ordinateur')), f(b('Tutor', 'Tuteur'), b('Windsor, available 24/7', 'Windsor, disponible 24 h/24'))],
      inc: [b('AI recommendations', 'Recommandations par IA'), b('Guided paths', 'Parcours guidés'), b('Progress tracking', 'Suivi de progression')] },
    { id: 'interview', icon: 'fa-microphone', name: b('Mock Interview Studio', 'Studio d’entretien simulé'), tag: b('3 simulated interviews · video feedback', '3 entretiens simulés · retour vidéo'),
      intro: b('Practise the interview in English before it counts. You are recorded, coached and given a written report on exactly what to improve.', 'Entraînez-vous à l’entretien en anglais avant qu’il ne compte. Vous êtes filmé, coaché et vous recevez un rapport écrit sur ce qu’il faut améliorer.'),
      who: [b('Job candidates applying to international or multinational employers', 'Candidats à des postes dans des entreprises internationales ou multinationales'), b('Professionals preparing for a promotion interview', 'Professionnels qui préparent un entretien de promotion')],
      outcomes: [b('Answer common interview questions clearly and briefly', 'Répondre clairement et brièvement aux questions classiques'), b('Describe your experience with strong, natural phrases', 'Décrire votre expérience avec des expressions solides et naturelles'), b('Watch yourself and fix habits that weaken your answers', 'Vous voir à l’écran et corriger les habitudes qui affaiblissent vos réponses')],
      modules: [b('Introducing yourself and your career', 'Se présenter et présenter son parcours'), b('Strengths, weaknesses and achievements', 'Forces, faiblesses et réalisations'), b('Behavioural questions with the PREP method', 'Questions comportementales avec la méthode PREP'), b('Your questions for the employer', 'Vos questions pour l’employeur')],
      facts: [f(b('Interviews', 'Entretiens'), b('3 simulations', '3 simulations')), f(b('Feedback', 'Retour'), b('Video and expert comments', 'Vidéo et commentaires d’un expert')), f(b('Report', 'Rapport'), b('Written improvement report', 'Rapport écrit d’amélioration'))],
      inc: [b('Video recording', 'Enregistrement vidéo'), b('Expert feedback', 'Retour d’un expert'), b('Written report', 'Rapport écrit')] },
    { id: 'club', icon: 'fa-users', name: b('Business English Club', 'Club Business English'), tag: b('Alumni membership', 'Abonnement alumni'),
      intro: b('Keep your English sharp after the course ends. Join live sessions, a members’ community and our newsletter.', 'Gardez votre anglais affûté après la fin du cours. Rejoignez des sessions en direct, une communauté de membres et notre newsletter.'),
      who: [b('Past Windsor learners who want to keep practising', 'Anciens apprenants Windsor qui veulent continuer à pratiquer'), b('Professionals who value a network of motivated peers', 'Professionnels qui apprécient un réseau de pairs motivés')],
      outcomes: [b('Keep speaking English every month', 'Continuer à parler anglais chaque mois'), b('Learn from guest topics and discussions', 'Apprendre grâce aux sujets invités et aux discussions'), b('Meet other professionals across the region', 'Rencontrer d’autres professionnels de la région')],
      modules: [b('Two webinars a month', 'Deux webinaires par mois'), b('Members’ WhatsApp group', 'Groupe WhatsApp réservé aux membres'), b('Windsor Dispatch newsletter', 'Newsletter Windsor Dispatch')],
      facts: [f(b('Billing', 'Facturation'), b('Monthly membership', 'Abonnement mensuel')), f(b('Live sessions', 'Sessions en direct'), b('2 webinars a month', '2 webinaires par mois')), f(b('Community', 'Communauté'), b('Members’ WhatsApp group', 'Groupe WhatsApp des membres'))],
      inc: [b('Webinars', 'Webinaires'), b('Members’ community', 'Communauté de membres'), b('Windsor Dispatch', 'Windsor Dispatch')] }
  ];

  function s(when, what) { return { when: when, what: what }; }
  var FLOW = {
    corporate: [s(b('1 h', '1 h'), b('Kick-off and level check for every learner', 'Lancement et test de niveau pour chaque apprenant')), s(b('12 h', '12 h'), b('Live workshops, face to face or on Zoom, built on your own work documents', 'Ateliers en direct, en présentiel ou sur Zoom, construits sur vos documents de travail')), s(b('5 h', '5 h'), b('Guided practice on the LMS with Windsor between sessions', 'Pratique guidée sur le LMS avec Windsor entre les séances')), s(b('2 h', '2 h'), b('Final assessment and written feedback', 'Évaluation finale et retour écrit'))],
    executive: [s(b('Session 1', 'Séance 1'), b('Needs analysis, goals and a baseline recording', 'Analyse des besoins, objectifs et enregistrement de référence')), s(b('Sessions 2 to 8', 'Séances 2 à 8'), b('Coaching on your real priorities, with homework between sessions', 'Coaching sur vos vraies priorités, avec exercices entre les séances')), s(b('Mid-point', 'Mi-parcours'), b('Progress review and plan adjustment', 'Point d’étape et ajustement du plan')), s(b('Final session', 'Dernière séance'), b('Assessment against your goals and a plan to keep improving', 'Évaluation par rapport à vos objectifs et plan pour continuer à progresser'))],
    certs: [s(b('2 h', '2 h'), b('Diagnostic test and a personal exam plan', 'Test diagnostique et plan d’examen personnel')), s(b('20 h', '20 h'), b('Skills workshops: listening, reading, speaking and writing', 'Ateliers de compétences : écoute, lecture, expression orale et écrite')), s(b('6 h', '6 h'), b('Full mock tests under exam conditions, with feedback', 'Examens blancs complets en conditions réelles, avec retour')), s(b('2 h', '2 h'), b('Final review and exam-day strategy', 'Révision finale et stratégie pour le jour de l’examen'))],
    workshops: [s(b('45 min', '45 min'), b('Warm-up and personal goals', 'Mise en route et objectifs personnels')), s(b('2 h 15 min', '2 h 15 min'), b('Key language and your own phrase bank', 'Langage clé et votre propre banque d’expressions')), s(b('3 h', '3 h'), b('Practice tasks and realistic role-plays', 'Exercices pratiques et jeux de rôle réalistes')), s(b('1 h', '1 h'), b('Feedback and an action plan for Monday morning', 'Retour et plan d’action pour lundi matin'))],
    startups: [s(b('Weeks 1 and 2', 'Semaines 1 et 2'), b('Your founder story and elevator pitch', 'Votre histoire de fondateur et votre elevator pitch')), s(b('Weeks 3 and 4', 'Semaines 3 et 4'), b('Pitch deck language, slide by slide', 'Le langage du pitch deck, diapositive par diapositive')), s(b('Weeks 5 and 6', 'Semaines 5 et 6'), b('Investor Q&A practice', 'Entraînement aux questions des investisseurs')), s(b('Weeks 7 and 8', 'Semaines 7 et 8'), b('Networking, follow-up emails and a final demo pitch', 'Réseautage, e-mails de suivi et pitch final de démonstration'))],
    b2b: [s(b('Before you start', 'Avant de commencer'), b('Free language audit of every participant', 'Audit linguistique gratuit de chaque participant')), s(b('Week 1', 'Semaine 1'), b('Custom plan and content built from your documents', 'Plan sur mesure et contenus construits à partir de vos documents')), s(b('Every week', 'Chaque semaine'), b('Live coaching on site or online, plus practice with Windsor', 'Coaching en direct sur site ou en ligne, plus pratique avec Windsor')), s(b('Every month', 'Chaque mois'), b('HR progress report with attendance, practice and CEFR movement', 'Rapport de progression pour les RH : présence, pratique et évolution CECRL'))],
    lms: [s(b('Day 1', 'Jour 1'), b('Placement check and personal goals', 'Test de placement et objectifs personnels')), s(b('Every day', 'Chaque jour'), b('Short exercises and Windsor, in minutes', 'Exercices courts et Windsor, en quelques minutes')), s(b('Every week', 'Chaque semaine'), b('Review of mistakes and a new guided path', 'Revue des erreurs et nouveau parcours guidé')), s(b('Every month', 'Chaque mois'), b('Progress snapshot against your CEFR target', 'Point de progression par rapport à votre objectif CECRL'))],
    interview: [s(b('Interview 1', 'Entretien 1'), b('Recorded baseline interview', 'Entretien de référence enregistré')), s(b('After each interview', 'Après chaque entretien'), b('Video review and expert comments', 'Revue vidéo et commentaires d’un expert')), s(b('Interviews 2 and 3', 'Entretiens 2 et 3'), b('Repeat with new questions and stronger answers', 'Nouvelle simulation avec d’autres questions et de meilleures réponses')), s(b('At the end', 'À la fin'), b('Written improvement report', 'Rapport écrit d’amélioration'))],
    club: [s(b('Twice a month', 'Deux fois par mois'), b('Live webinar on a business topic', 'Webinaire en direct sur un thème professionnel')), s(b('Every day', 'Chaque jour'), b('Members’ WhatsApp group for questions and practice', 'Groupe WhatsApp des membres pour questions et pratique')), s(b('Every month', 'Chaque mois'), b('Windsor Dispatch newsletter', 'Newsletter Windsor Dispatch'))]
  };
  P.forEach(function (x) { x.flow = FLOW[x.id]; });
  /* small-group option on the group programmes */
  P[0].facts[1] = f(b('Group size', 'Taille du groupe'), b('8 to 12, or a small group of 4 to 6 on request', '8 à 12, ou petit groupe de 4 à 6 sur demande'));
  P[2].facts.push(f(b('Groups', 'Groupes'), b('Small group of 4 to 6 on request', 'Petit groupe de 4 à 6 sur demande')));
  window.WBE_DATA.PROGRAMMES = P;
})();
