/* Full programme content: syllabus, assessment, sample lesson and FAQ. Every string is { en, fr }.
   Hours and formats match the programme cards. Module topics and sample lessons are drafts for Windsor to confirm. */
(function () {
  function b(en, fr) { return { en: en, fr: fr }; }
  function m(t, h, pts, out) { return { t: t, h: h, pts: pts, out: out }; }
  function q(qu, an) { return { q: qu, a: an }; }

  var S = {
    corporate: {
      syllabus: [
        m(b('Kick-off and level check', 'Lancement et test de niveau'), b('1 h', '1 h'), [b('A placement check places each learner on the CEFR scale', 'Un test de placement situe chaque apprenant sur l’échelle du CECRL'), b('Goals and the real work situations your team faces', 'Objectifs et situations de travail réelles de votre équipe'), b('A first look at the Windsor LMS and the AI tutor', 'Première découverte du LMS Windsor et du tuteur IA')], b('Start in the right group with a personal target.', 'Démarrer dans le bon groupe avec un objectif personnel.')),
        m(b('Emails and messages that get answers', 'E-mails et messages qui obtiennent une réponse'), b('4 h', '4 h'), [b('Subject lines, structure and tone with the PREP framework', 'Objets, structure et ton avec la méthode PREP'), b('Requests, reminders, follow-ups and polite refusals', 'Demandes, relances, suivis et refus polis'), b('Common errors: prepositions, false friends, word order', 'Erreurs fréquentes : prépositions, faux amis, ordre des mots')], b('Write a clear, polite email in a few minutes.', 'Rédiger en quelques minutes un e-mail clair et poli.')),
        m(b('Meetings and calls', 'Réunions et appels'), b('4 h', '4 h'), [b('Opening, clarifying, agreeing, disagreeing and interrupting politely', 'Ouvrir, clarifier, approuver, nuancer et interrompre poliment'), b('Phone and Zoom language, including technical problems', 'Langage du téléphone et de Zoom, y compris les problèmes techniques'), b('Small talk and building rapport', 'Conversation informelle et création de lien')], b('Take part in meetings and calls with confidence.', 'Participer aux réunions et aux appels avec assurance.')),
        m(b('Presenting updates and figures', 'Présenter des points d’étape et des chiffres'), b('4 h', '4 h'), [b('Structure an update in 60 seconds with PREP', 'Structurer un point d’étape en 60 secondes avec PREP'), b('Describe trends, targets and numbers accurately', 'Décrire avec précision des tendances, des objectifs et des chiffres'), b('Answer questions and handle surprises', 'Répondre aux questions et gérer l’imprévu')], b('Present results clearly to colleagues and managers.', 'Présenter clairement des résultats à des collègues et à des responsables.')),
        m(b('Guided practice on the LMS with Windsor', 'Pratique guidée sur le LMS avec Windsor'), b('5 h between sessions', '5 h entre les séances'), [b('Short daily exercises matched to your level', 'Exercices quotidiens courts adaptés à votre niveau'), b('Instant feedback on vocabulary, grammar and tone', 'Retour immédiat sur le vocabulaire, la grammaire et le ton'), b('Practice with your sector’s vocabulary', 'Entraînement avec le vocabulaire de votre secteur')], b('Keep progressing between live sessions.', 'Continuer à progresser entre les séances en direct.')),
        m(b('Final assessment and feedback', 'Évaluation finale et retour'), b('2 h', '2 h'), [b('A final task assessed against the same CEFR descriptors', 'Une épreuve finale évaluée selon les mêmes descripteurs du CECRL'), b('Written feedback for every learner', 'Un retour écrit pour chaque apprenant'), b('Next steps to keep improving', 'Les prochaines étapes pour continuer à progresser')], b('See how far you have moved and what to do next.', 'Mesurer le chemin parcouru et savoir quoi faire ensuite.')),
        m(b('Added in the 40 h format', 'Ajouté au format de 40 h'), b('+20 h', '+20 h'), [b('Negotiating and solving problems', 'Négocier et résoudre des problèmes'), b('Reports, proposals and minutes', 'Rapports, propositions et comptes rendus'), b('Intercultural communication and sector-specific modules', 'Communication interculturelle et modules propres à votre secteur')], b('Go deeper on the skills your roles need most.', 'Approfondir les compétences dont vos fonctions ont le plus besoin.'))
      ],
      assess: b('Every learner takes a level check at the start and a final assessment against the same CEFR descriptors, with written feedback. A certificate of completion is issued when attendance requirements in our enrolment terms are met.', 'Chaque apprenant passe un test de niveau au début et une évaluation finale selon les mêmes descripteurs du CECRL, avec un retour écrit. Une attestation de participation est délivrée lorsque les conditions d’assiduité de nos conditions d’inscription sont remplies.'),
      prereq: b('None. A free level check places each learner in the right group.', 'Aucun. Un test de niveau gratuit place chaque apprenant dans le bon groupe.'),
      schedule: b('Sessions are agreed with your company, for example early morning, lunch time, evenings or weekends. The 20 h format usually runs over 8 to 10 weeks (indicative).', 'Les séances sont fixées avec votre entreprise : tôt le matin, à midi, le soir ou le week-end. Le format de 20 h s’étale en général sur 8 à 10 semaines (à titre indicatif).'),
      sample: { title: b('Rewrite a weak email with PREP', 'Réécrire un e-mail faible avec PREP'), steps: [
        b('Read this email: “Hello, I want the report. When will you finish?”', 'Lisez cet e-mail : « Hello, I want the report. When will you finish? »'),
        b('In pairs, find what is missing: a polite tone, a reason and a deadline.', 'Par deux, repérez ce qui manque : un ton poli, une raison et une échéance.'),
        b('Rebuild it with PREP: Point (the request), Reason (why you need it), Example or detail (the deadline), Point (thanks and next step).', 'Reconstruisez-le avec PREP : Point (la demande), Raison (pourquoi), Exemple ou détail (l’échéance), Point (remerciements et suite).'),
        b('Model answer: “Could you please send me the Q3 report by Thursday COB? I need it for Friday’s board meeting. Thank you, and let me know if anything is unclear.”', 'Réponse type : « Could you please send me the Q3 report by Thursday COB? I need it for Friday’s board meeting. Thank you, and let me know if anything is unclear. »'),
        b('Write your own version from a real situation, then check tone and prepositions with Windsor.', 'Rédigez votre propre version à partir d’une situation réelle, puis vérifiez le ton et les prépositions avec Windsor.')] },
      faq: [
        q(b('Can colleagues from different departments join one group?', 'Des collègues de services différents peuvent-ils former un groupe ?'), b('Yes. We group by CEFR level first and, where possible, by type of role, so the examples fit everyone.', 'Oui. Nous regroupons d’abord par niveau CECRL puis, si possible, par type de fonction, pour que les exemples conviennent à tous.')),
        q(b('Is it face to face or online?', 'Est-ce en présentiel ou en ligne ?'), b('Both. The programme is hybrid: live sessions face to face or on Zoom, plus practice on the LMS.', 'Les deux. Le programme est hybride : séances en direct en présentiel ou sur Zoom, plus pratique sur le LMS.')),
        q(b('What if someone misses a session?', 'Que se passe-t-il si quelqu’un manque une séance ?'), b('Group sessions cannot be moved, but we point the learner to the practice material for the missed session.', 'Les séances de groupe ne peuvent pas être déplacées, mais nous orientons l’apprenant vers le matériel de la séance manquée.'))
      ]
    },

    executive: {
      syllabus: [
        m(b('Diagnostic and goal setting', 'Diagnostic et définition des objectifs'), b('Session 1', 'Séance 1'), [b('A baseline recording of how you speak today', 'Un enregistrement de référence de votre expression actuelle'), b('Your top situations: board updates, negotiations, travel, media', 'Vos principales situations : conseil, négociations, déplacements, médias'), b('A personal plan with measurable goals', 'Un plan personnel avec des objectifs mesurables')], b('Know exactly what to improve first.', 'Savoir précisément quoi améliorer en priorité.')),
        m(b('Leading meetings and conference calls', 'Diriger des réunions et des conférences téléphoniques'), b('Sessions 2 to 3', 'Séances 2 à 3'), [b('Setting the agenda, managing time and summarising actions', 'Fixer l’ordre du jour, gérer le temps et résumer les actions'), b('Handling interruptions, silence and strong opinions', 'Gérer interruptions, silences et opinions tranchées'), b('Chairing across time zones and cultures', 'Présider entre fuseaux horaires et cultures')], b('Run a meeting in English with authority.', 'Conduire une réunion en anglais avec autorité.')),
        m(b('Negotiation and persuasion', 'Négociation et persuasion'), b('Sessions 4 to 5', 'Séances 4 à 5'), [b('Opening positions, concessions and closing the deal', 'Positions de départ, concessions et conclusion de l’accord'), b('Diplomatic ways to say no or ask for more', 'Façons diplomatiques de dire non ou de demander plus'), b('Confirming agreements in writing', 'Confirmer les accords par écrit')], b('Negotiate calmly and confirm what was agreed.', 'Négocier calmement et confirmer ce qui a été convenu.')),
        m(b('Presenting with authority', 'Présenter avec autorité'), b('Sessions 6 to 7', 'Séances 6 à 7'), [b('The PREP structure for executive messages', 'La structure PREP pour les messages de dirigeant'), b('Voice, pace and emphasis', 'Voix, rythme et mise en relief'), b('Using numbers and visuals without losing the room', 'Utiliser chiffres et visuels sans perdre l’auditoire')], b('Deliver a clear, memorable presentation.', 'Délivrer une présentation claire et mémorable.')),
        m(b('Written communication at senior level', 'Communication écrite de haut niveau'), b('Sessions 8 to 9', 'Séances 8 à 9'), [b('Emails that decide, not just inform', 'Des e-mails qui font décider, pas seulement informer'), b('Short reports, briefings and LinkedIn posts', 'Notes courtes, comptes rendus et publications LinkedIn'), b('Tone: warm, direct and respectful', 'Ton : chaleureux, direct et respectueux')], b('Write with the tone your role requires.', 'Écrire avec le ton que votre rôle exige.')),
        m(b('Q&A, difficult conversations and media', 'Questions-réponses, conversations difficiles et médias'), b('20 and 30 session formats', 'Formats de 20 et 30 séances'), [b('Answering hard questions without freezing', 'Répondre aux questions difficiles sans se bloquer'), b('Bridging, reframing and staying on message', 'Rebondir, reformuler et tenir son message'), b('Short interviews and statements', 'Brèves interviews et déclarations')], b('Stay composed under pressure.', 'Rester serein sous pression.')),
        m(b('Leadership networking and a personal project', 'Réseautage de dirigeant et projet personnel'), b('30 session format', 'Format de 30 séances'), [b('Introducing yourself and your organisation at events', 'Se présenter et présenter son organisation lors d’événements'), b('Preparing a real board presentation or negotiation with your coach', 'Préparer avec votre coach une vraie présentation au conseil ou une négociation'), b('A final plan to keep improving', 'Un plan final pour continuer à progresser')], b('Use English for a real, high-stakes task.', 'Utiliser l’anglais pour une vraie tâche à fort enjeu.'))
      ],
      assess: b('A baseline recording in session 1, a mid-point review and a final assessment against your own goals, with progress notes after sessions.', 'Un enregistrement de référence à la séance 1, un point d’étape à mi-parcours et une évaluation finale par rapport à vos propres objectifs, avec des notes de progression après les séances.'),
      prereq: b('None. Coaching starts at your current level.', 'Aucun. Le coaching démarre à votre niveau actuel.'),
      schedule: b('Flexible hours agreed with you, in Abidjan or online. Individual sessions can be moved if you tell us at least 24 hours before.', 'Horaires flexibles convenus avec vous, à Abidjan ou en ligne. Les séances individuelles peuvent être déplacées si vous nous prévenez au moins 24 heures à l’avance.'),
      sample: { title: b('Answer a tough question in 60 seconds', 'Répondre à une question difficile en 60 secondes'), steps: [
        b('Your coach asks: “Why did the project miss its deadline?”', 'Votre coach demande : « Why did the project miss its deadline? »'),
        b('Bridge first: “That is a fair question. What matters now is where we are and how we recover.”', 'Faites le pont d’abord : « That is a fair question. What matters now is where we are and how we recover. »'),
        b('Answer with PREP: Point (the cause in one sentence), Reason (what happened), Example (one fact), Point (the recovery plan).', 'Répondez avec PREP : Point (la cause en une phrase), Raison (ce qui s’est passé), Exemple (un fait), Point (le plan de rattrapage).'),
        b('Record yourself, listen back and trim filler words.', 'Enregistrez-vous, réécoutez-vous et supprimez les mots de remplissage.'),
        b('Repeat with a harder question and compare the two recordings.', 'Recommencez avec une question plus difficile et comparez les deux enregistrements.')] },
      faq: [
        q(b('Where do sessions take place?', 'Où se déroulent les séances ?'), b('In Abidjan, at your office or ours, or online, whichever suits your schedule.', 'À Abidjan, dans vos bureaux ou les nôtres, ou en ligne, selon votre emploi du temps.')),
        q(b('Do you work on my own documents?', 'Travaillez-vous sur mes propres documents ?'), b('Yes. Content is tailored to your industry and your real situations. Anything you share is handled under our privacy policy.', 'Oui. Le contenu est adapté à votre secteur et à vos situations réelles. Tout ce que vous partagez est traité selon notre politique de confidentialité.')),
        q(b('How do I choose between 10, 20 and 30 sessions?', 'Comment choisir entre 10, 20 et 30 séances ?'), b('We recommend a format after the diagnostic. Ten sessions cover the essentials, twenty add pressure situations, and thirty add a real project.', 'Nous recommandons un format après le diagnostic. Dix séances couvrent l’essentiel, vingt ajoutent les situations sous pression, trente ajoutent un projet réel.'))
      ]
    },

    certs: {
      syllabus: [
        m(b('Diagnostic and exam plan', 'Diagnostic et plan d’examen'), b('2 h', '2 h'), [b('A diagnostic test in the exam format', 'Un test diagnostique au format de l’examen'), b('Choosing the right exam for your goal: TOEIC, TOEFL iBT or Linguaskill Business', 'Choisir l’examen adapté à votre objectif : TOEIC, TOEFL iBT ou Linguaskill Business'), b('How a computer-adaptive test such as Linguaskill differs from a fixed-form test such as TOEIC', 'En quoi un test adaptatif sur ordinateur comme Linguaskill diffère d’un test à format fixe comme le TOEIC'), b('A personal study plan', 'Un plan de travail personnel')], b('Know your starting score and your target.', 'Connaître votre score de départ et votre objectif.')),
        m(b('Listening strategies', 'Stratégies d’écoute'), b('5 h', '5 h'), [b('Predicting answers before the audio starts', 'Anticiper les réponses avant l’audio'), b('Accents, speed and distractors', 'Accents, débit et pièges'), b('Note-taking shortcuts', 'Raccourcis de prise de notes')], b('Follow longer recordings and pick the right answer.', 'Suivre des enregistrements plus longs et choisir la bonne réponse.')),
        m(b('Reading strategies', 'Stratégies de lecture'), b('5 h', '5 h'), [b('Skimming, scanning and reading questions first', 'Lecture rapide, repérage et lecture des questions d’abord'), b('Vocabulary in context and business collocations', 'Vocabulaire en contexte et collocations professionnelles'), b('Eliminating distractors', 'Éliminer les réponses pièges')], b('Read faster and answer with more accuracy.', 'Lire plus vite et répondre avec plus de précision.')),
        m(b('Speaking tasks', 'Épreuves orales'), b('5 h', '5 h'), [b('Structuring answers under time pressure', 'Structurer ses réponses sous contrainte de temps'), b('Fluency, pronunciation and linking ideas', 'Aisance, prononciation et enchaînement des idées'), b('Describing graphs and giving opinions', 'Décrire des graphiques et donner son opinion')], b('Speak clearly for the full time allowed.', 'Parler clairement pendant tout le temps imparti.')),
        m(b('Writing tasks', 'Épreuves écrites'), b('5 h', '5 h'), [b('Emails, reports and short essays in exam format', 'E-mails, rapports et courts essais au format d’examen'), b('Planning, paragraphing and checking', 'Planification, paragraphes et relecture'), b('Typical errors to avoid', 'Erreurs typiques à éviter')], b('Write accurate, well-organised answers on time.', 'Rédiger des réponses justes et bien organisées dans le temps.')),
        m(b('Full mock tests with feedback', 'Examens blancs complets avec retour'), b('6 h', '6 h'), [b('Complete tests under real conditions', 'Tests complets en conditions réelles'), b('Error analysis by skill and question type', 'Analyse des erreurs par compétence et type de question'), b('Time-management drills', 'Exercices de gestion du temps')], b('Arrive on exam day knowing what to expect.', 'Arriver le jour de l’examen en sachant à quoi s’attendre.')),
        m(b('Final review and exam-day strategy', 'Révision finale et stratégie du jour J'), b('2 h', '2 h'), [b('Targeted revision of your weakest areas', 'Révision ciblée de vos points faibles'), b('Registration, documents and logistics', 'Inscription, documents et logistique'), b('Staying calm and managing stress', 'Rester calme et gérer le stress')], b('Be fully prepared on the day.', 'Être pleinement prêt le jour J.'))
      ],
      assess: b('A diagnostic at the start and full mock tests with error analysis. Exam fees are paid separately to the exam body. We prepare you carefully, but we cannot promise a particular score or level.', 'Un diagnostic au départ et des examens blancs complets avec analyse des erreurs. Les frais d’examen sont payés séparément à l’organisme d’examen. Nous vous préparons avec soin, mais nous ne pouvons pas promettre un score ou un niveau précis.'),
      prereq: b('A basic working level of English is recommended. The diagnostic confirms whether you are ready for your chosen exam.', 'Un niveau de travail de base en anglais est recommandé. Le diagnostic confirme si vous êtes prêt pour l’examen choisi.'),
      schedule: b('30 hours, with a schedule agreed around your exam date. Tests are booked separately with an approved test centre, and we advise you on this at the diagnostic. A small group of 4 to 6 is available on request.', '30 heures, avec un calendrier fixé en fonction de la date de votre examen. Les tests se réservent séparément auprès d’un centre d’examen agréé, et nous vous conseillons à ce sujet lors du diagnostic. Un petit groupe de 4 à 6 personnes est possible sur demande.'),
      sample: { title: b('A timed reading task', 'Une épreuve de lecture chronométrée'), steps: [
        b('Spend 30 seconds skimming the headings and first lines of the text.', 'Consacrez 30 secondes à survoler les titres et les premières lignes du texte.'),
        b('Read the questions before the text so you know what to look for.', 'Lisez les questions avant le texte pour savoir quoi chercher.'),
        b('Scan for keywords and mark the paragraph where each answer lives.', 'Repérez les mots clés et notez le paragraphe où se trouve chaque réponse.'),
        b('Eliminate two distractors, then choose between the last two.', 'Éliminez deux réponses pièges, puis choisissez entre les deux dernières.'),
        b('Review your errors by type: vocabulary, inference or time.', 'Analysez vos erreurs par type : vocabulaire, inférence ou temps.')] },
      faq: [
        q(b('Which exam should I take?', 'Quel examen dois-je passer ?'), b('It depends on your employer or institution. TOEIC and TOEFL iBT are widely requested. Linguaskill Business is Cambridge’s online workplace-English test, reported on the CEFR scale. The diagnostic includes advice on the best exam for your goal.', 'Cela dépend de votre employeur ou de votre établissement. Le TOEIC et le TOEFL iBT sont très demandés. Linguaskill Business est le test d’anglais professionnel en ligne de Cambridge, avec des résultats sur l’échelle du CECRL. Le diagnostic inclut un conseil sur l’examen le plus adapté à votre objectif.')),
        q(b('Are exam fees included?', 'Les frais d’examen sont-ils inclus ?'), b('No. Exam fees are paid separately to the exam body. Study materials and mock tests are included.', 'Non. Les frais d’examen sont payés séparément à l’organisme d’examen. Les supports et les examens blancs sont inclus.')),
        q(b('Can you guarantee a score?', 'Pouvez-vous garantir un score ?'), b('No honest provider can. We guarantee focused preparation, real practice and honest feedback.', 'Aucun organisme sérieux ne le peut. Nous garantissons une préparation ciblée, une vraie pratique et un retour honnête.')),
        q(b('What about BULATS and the Cambridge Business English Certificates (BEC)?', 'Et BULATS et les Business English Certificates (BEC) de Cambridge ?'), b('Cambridge retired BULATS in December 2019 and no longer offers BEC outside China. It recommends Linguaskill Business as the alternative, so that is what we prepare for.', 'Cambridge a retiré BULATS en décembre 2019 et ne propose plus les BEC en dehors de la Chine. Cambridge recommande Linguaskill Business comme alternative : c’est donc ce test que nous préparons.'))
      ]
    },

    workshops: {
      syllabus: [
        m(b('WW-01 Business Negotiation', 'WW-01 Négociation commerciale'), b('7 h', '7 h'), [b('Opening positions, questions that uncover needs', 'Positions de départ, questions qui révèlent les besoins'), b('Concessions: “If you could…, we could…”', 'Concessions : « If you could…, we could… »'), b('Closing, summarising and confirming in writing', 'Conclure, résumer et confirmer par écrit')], b('Negotiate a realistic deal in English.', 'Négocier un accord réaliste en anglais.')),
        m(b('WW-02 High-Impact Presentations', 'WW-02 Présentations percutantes'), b('7 h', '7 h'), [b('PREP structure and strong openings', 'Structure PREP et ouvertures marquantes'), b('Signposting, emphasis and handling numbers', 'Fil conducteur, mise en relief et présentation des chiffres'), b('Q&A and recovering from mistakes', 'Questions-réponses et rattrapage après une erreur')], b('Deliver a five-minute presentation with confidence.', 'Faire une présentation de cinq minutes avec assurance.')),
        m(b('WW-03 Professional Writing', 'WW-03 Rédaction professionnelle'), b('7 h', '7 h'), [b('Email structure, tone and subject lines', 'Structure, ton et objet des e-mails'), b('Short reports and proposals', 'Rapports courts et propositions'), b('An editing checklist you keep using', 'Une liste de relecture que vous continuerez à utiliser')], b('Write documents that get read and get action.', 'Rédiger des documents lus et suivis d’effet.')),
        m(b('WW-04 Meetings and Conference Calls', 'WW-04 Réunions et conférences téléphoniques'), b('7 h', '7 h'), [b('Chairing and taking part in meetings', 'Animer une réunion et y participer'), b('Phone and Zoom etiquette and repair phrases', 'Savoir-vivre au téléphone et sur Zoom, et formules de rattrapage'), b('Summarising decisions and action points', 'Résumer décisions et points d’action')], b('Lead and join international calls with confidence.', 'Animer et rejoindre des appels internationaux avec assurance.')),
        m(b('WW-05 LinkedIn Optimisation', 'WW-05 Optimisation LinkedIn'), b('7 h', '7 h'), [b('A headline and About section that attract the right people', 'Un titre et une section À propos qui attirent les bonnes personnes'), b('Experience bullets built around achievements', 'Des expériences construites autour de réalisations'), b('Connection requests and short outreach messages', 'Demandes de connexion et courts messages d’approche')], b('Leave with an English profile ready to publish.', 'Repartir avec un profil en anglais prêt à publier.'))
      ],
      assess: b('Practice tasks and role-plays all day with feedback from your coach, and a personal action plan at the end. A certificate of completion is issued when attendance requirements in our enrolment terms are met.', 'Exercices pratiques et jeux de rôle toute la journée avec le retour de votre coach, et un plan d’action personnel à la fin. Une attestation de participation est délivrée lorsque les conditions d’assiduité de nos conditions d’inscription sont remplies.'),
      prereq: b('A basic working level of English. A free level check confirms the right workshop for you.', 'Un niveau de travail de base en anglais. Un test de niveau gratuit confirme l’atelier qui vous convient.'),
      schedule: b('One day of 7 hours: 45 minutes warm-up, 2 h 15 key language, 3 h practice and role-plays, 1 h feedback and action plan. Abidjan, online, or at your offices.', 'Une journée de 7 heures : 45 min de mise en route, 2 h 15 de langage clé, 3 h de pratique et de jeux de rôle, 1 h de retour et de plan d’action. À Abidjan, en ligne ou dans vos locaux.'),
      sample: { title: b('Make a concession without losing ground', 'Faire une concession sans perdre de terrain'), steps: [
        b('Situation: a supplier asks for payment in 15 days. You need 30.', 'Situation : un fournisseur demande un paiement à 15 jours. Il vous en faut 30.'),
        b('Learn the pattern: “If you could extend to 30 days, we could increase the order.”', 'Apprenez la structure : « If you could extend to 30 days, we could increase the order. »'),
        b('Role-play in pairs, then swap roles and change the numbers.', 'Jeu de rôle à deux, puis échangez les rôles et changez les chiffres.'),
        b('Confirm in writing: “To confirm what we agreed: payment in 30 days, order increased by 10%.”', 'Confirmez par écrit : « To confirm what we agreed: payment in 30 days, order increased by 10%. »')] },
      faq: [
        q(b('Can I attend more than one workshop?', 'Puis-je suivre plusieurs ateliers ?'), b('Yes. Each workshop is a separate day on a separate skill, and you can combine them over time.', 'Oui. Chaque atelier est une journée distincte sur une compétence distincte, et vous pouvez les combiner au fil du temps.')),
        q(b('Can you run a workshop for my team only?', 'Pouvez-vous animer un atelier pour mon équipe seulement ?'), b('Yes. Any workshop can run at your offices, scheduled around your calendar.', 'Oui. Tout atelier peut se dérouler dans vos locaux, selon votre calendrier.')),
        q(b('What do I leave with?', 'Avec quoi est-ce que je repars ?'), b('Your own phrase bank, an action plan for the next morning, and a certificate of completion when attendance requirements are met.', 'Votre propre banque d’expressions, un plan d’action pour le lendemain et une attestation de participation lorsque les conditions d’assiduité sont remplies.'))
      ]
    },

    startups: {
      syllabus: [
        m(b('Weeks 1 and 2: Founder story and elevator pitch', 'Semaines 1 et 2 : histoire du fondateur et elevator pitch'), b('8 h', '8 h'), [b('A baseline pitch recorded in week 1', 'Un pitch de référence enregistré en semaine 1'), b('Problem, solution, traction and ask in 30 seconds', 'Problème, solution, traction et demande en 30 secondes'), b('Your founder story in clear, simple English', 'Votre histoire de fondateur en anglais simple et clair')], b('Introduce your company clearly in any setting.', 'Présenter clairement votre entreprise dans n’importe quel cadre.')),
        m(b('Weeks 3 and 4: Pitch deck language', 'Semaines 3 et 4 : le langage du pitch deck'), b('8 h', '8 h'), [b('What to say on each slide', 'Ce qu’il faut dire sur chaque diapositive'), b('Describing market size, growth and business model', 'Décrire la taille du marché, la croissance et le modèle économique'), b('Using numbers and charts in speech', 'Parler des chiffres et des graphiques')], b('Present a full deck smoothly.', 'Présenter un deck complet avec fluidité.')),
        m(b('Weeks 5 and 6: Investor Q&A', 'Semaines 5 et 6 : questions des investisseurs'), b('8 h', '8 h'), [b('The twenty questions investors always ask', 'Les vingt questions que les investisseurs posent toujours'), b('Handling objections and honest unknowns', 'Répondre aux objections et reconnaître ce qu’on ne sait pas'), b('Valuation, funding and terms vocabulary', 'Vocabulaire de la valorisation, du financement et des conditions')], b('Answer investor questions without freezing.', 'Répondre aux investisseurs sans se bloquer.')),
        m(b('Weeks 7 and 8: Networking and final demo pitch', 'Semaines 7 et 8 : réseautage et pitch final'), b('8 h', '8 h'), [b('Introductions, small talk and follow-up emails', 'Présentations, conversation informelle et e-mails de suivi'), b('A final demo pitch with feedback from coaches and peers', 'Un pitch final de démonstration avec retours des coachs et des pairs'), b('Your next steps to keep practising', 'Vos prochaines étapes pour continuer à pratiquer')], b('Network and pitch in English at international events.', 'Réseauter et pitcher en anglais lors d’événements internationaux.'))
      ],
      assess: b('Your week 1 recording is compared with the final demo pitch in week 8, with feedback from your coach and the cohort.', 'Votre enregistrement de la semaine 1 est comparé au pitch final de la semaine 8, avec les retours de votre coach et de la cohorte.'),
      prereq: b('A working level of English and a business idea or company to pitch.', 'Un niveau de travail en anglais et une idée d’entreprise ou une société à présenter.'),
      schedule: b('8 weeks, 4 hours a week, in Abidjan or online. Cohort start dates are announced in our Events section.', '8 semaines, 4 heures par semaine, à Abidjan ou en ligne. Les dates de démarrage des cohortes sont annoncées dans notre section Événements.'),
      sample: { title: b('The 30-second pitch formula', 'La formule du pitch de 30 secondes'), steps: [
        b('Problem: “Every month, small farmers lose 20% of their harvest because they cannot reach buyers.”', 'Problème : « Every month, small farmers lose 20% of their harvest because they cannot reach buyers. »'),
        b('Solution: “We connect them to verified buyers through a simple mobile app.”', 'Solution : « We connect them to verified buyers through a simple mobile app. »'),
        b('Traction: “In three months we signed 200 farmers and two exporters.”', 'Traction : « In three months we signed 200 farmers and two exporters. »'),
        b('Ask: “We are raising a seed round to expand to three more regions.”', 'Demande : « We are raising a seed round to expand to three more regions. »'),
        b('Write your own four sentences, record them and refine with your coach. (The examples above are illustrative.)', 'Écrivez vos quatre phrases, enregistrez-vous et affinez avec votre coach. (Les exemples ci-dessus sont fictifs.)')] },
      faq: [
        q(b('Do I need a pitch deck already?', 'Ai-je besoin d’un pitch deck dès maintenant ?'), b('No. It helps, but we build the language slide by slide, and you can improve the deck as you go.', 'Non. C’est utile, mais nous construisons le langage diapositive par diapositive, et vous pouvez améliorer le deck au fil du programme.')),
        q(b('Is it individual or group?', 'Est-ce individuel ou en groupe ?'), b('It is a cohort, so you practise with other founders and give each other feedback.', 'C’est une cohorte : vous pratiquez avec d’autres entrepreneurs et vous vous donnez des retours.')),
        q(b('Do you introduce me to investors?', 'Me présentez-vous à des investisseurs ?'), b('No. We train your English and your delivery. We do not promise introductions or funding.', 'Non. Nous travaillons votre anglais et votre prestation. Nous ne promettons ni présentations ni financement.'))
      ]
    },

    b2b: {
      syllabus: [
        m(b('Free language audit', 'Audit linguistique gratuit'), b('Before you start', 'Avant de commencer'), [b('A level check for each participant on the CEFR scale', 'Un test de niveau pour chaque participant sur l’échelle du CECRL'), b('Interviews with HR and managers about real needs', 'Entretiens avec les RH et les responsables sur les besoins réels'), b('A short report with recommendations', 'Un court rapport avec des recommandations')], b('See where each person stands and what the team needs.', 'Voir où en est chaque personne et ce dont l’équipe a besoin.')),
        m(b('Custom plan and content', 'Plan et contenus sur mesure'), b('Week 1', 'Semaine 1'), [b('Learning goals tied to business outcomes', 'Objectifs de formation liés à vos résultats'), b('Content built from your own emails, contracts and meetings', 'Contenus construits à partir de vos propres e-mails, contrats et réunions'), b('A calendar that fits your operations', 'Un calendrier compatible avec votre activité')], b('Agree a plan your leadership can approve.', 'Convenir d’un plan que votre direction peut valider.')),
        m(b('Live coaching and practice', 'Coaching en direct et pratique'), b('Every week', 'Chaque semaine'), [b('Live sessions on site or online for teams of 10 per module', 'Séances en direct sur site ou en ligne pour des équipes de 10 par module'), b('Daily practice on the Windsor LMS with the AI tutor', 'Pratique quotidienne sur le LMS Windsor avec le tuteur IA'), b('Sector vocabulary and real work tasks', 'Vocabulaire sectoriel et tâches de travail réelles')], b('Use English on the job from the first weeks.', 'Utiliser l’anglais au travail dès les premières semaines.')),
        m(b('Monthly HR progress report', 'Rapport mensuel de progression pour les RH'), b('Every month', 'Chaque mois'), [b('Attendance and practice activity', 'Présence et activité de pratique'), b('CEFR movement for each learner', 'Évolution CECRL de chaque apprenant'), b('Risks, wins and next actions', 'Risques, réussites et prochaines actions')], b('Show leadership clear progress every month.', 'Montrer chaque mois à la direction une progression claire.')),
        m(b('Closing review', 'Bilan de clôture'), b('End of programme', 'Fin du programme'), [b('A final assessment against the starting level', 'Une évaluation finale comparée au niveau de départ'), b('Recommendations for the next phase', 'Recommandations pour la phase suivante'), b('Certificates of completion where requirements are met', 'Attestations de participation lorsque les conditions sont remplies')], b('Decide with evidence what to do next.', 'Décider sur des faits de la suite à donner.'))
      ],
      assess: b('A CEFR check before and after, attendance records and practice activity, summarised in the monthly report. Learners are told what is reported to the sponsor, as set out in our privacy policy.', 'Un test CECRL avant et après, les présences et l’activité de pratique, résumés dans le rapport mensuel. Les apprenants savent ce qui est rapporté au sponsor, comme le prévoit notre politique de confidentialité.'),
      prereq: b('Teams of any English level. The audit groups people by level and role.', 'Équipes de tout niveau d’anglais. L’audit regroupe les personnes par niveau et par fonction.'),
      schedule: b('Agreed with your company: on site in Abidjan, online, or both. Modules are priced per team of 10, quoted on request.', 'Convenu avec votre entreprise : sur site à Abidjan, en ligne ou les deux. Les modules sont chiffrés par équipe de 10, sur devis.'),
      sample: { title: b('A monthly HR report, what it shows', 'Un rapport mensuel RH : ce qu’il montre'), steps: [
        b('Attendance: how many learners attended each session.', 'Présence : combien d’apprenants ont assisté à chaque séance.'),
        b('Practice: how often each learner used the AI tutor and the LMS.', 'Pratique : la fréquence d’utilisation du tuteur IA et du LMS par apprenant.'),
        b('Progress: CEFR movement against the starting level.', 'Progression : l’évolution du niveau CECRL par rapport au point de départ.'),
        b('Actions: who needs extra support and what we will do about it.', 'Actions : qui a besoin d’un soutien supplémentaire et ce que nous ferons.'),
        b('See the illustrative report on this page for the layout.', 'Voyez le rapport illustratif de cette page pour la mise en forme.')] },
      faq: [
        q(b('Can we train managers and staff separately?', 'Peut-on former séparément les cadres et les employés ?'), b('Yes. Modules are built per team, so each group gets content that fits its role.', 'Oui. Les modules sont construits par équipe : chaque groupe reçoit un contenu adapté à sa fonction.')),
        q(b('What does HR see?', 'Que voient les RH ?'), b('Attendance, practice activity and progress, plus recommendations. Learners know in advance what is reported.', 'La présence, l’activité de pratique et la progression, plus des recommandations. Les apprenants savent à l’avance ce qui est rapporté.')),
        q(b('Where does training take place?', 'Où se déroule la formation ?'), b('At your offices in Abidjan, online across the UEMOA region, or a mix of both.', 'Dans vos locaux à Abidjan, en ligne dans toute la région UEMOA, ou un mélange des deux.'))
      ]
    },

    lms: {
      syllabus: [
        m(b('Placement and goals', 'Placement et objectifs'), b('Day 1', 'Jour 1'), [b('A short check places you on the CEFR scale', 'Un court test vous situe sur l’échelle du CECRL'), b('You choose your goals and work situations', 'Vous choisissez vos objectifs et vos situations de travail'), b('Your first guided path is built for you', 'Votre premier parcours guidé est construit pour vous')], b('Start with a path that fits you.', 'Démarrer avec un parcours adapté à vous.')),
        m(b('Guided learning paths', 'Parcours d’apprentissage guidés'), b('Ongoing', 'En continu'), [b('Step-by-step paths by skill and sector', 'Parcours pas à pas par compétence et par secteur'), b('Recommendations that follow how you learn', 'Recommandations qui suivent votre façon d’apprendre'), b('Review of earlier mistakes', 'Révision des erreurs passées')], b('Always know what to practise next.', 'Toujours savoir quoi pratiquer ensuite.')),
        m(b('Quick exercises with instant feedback', 'Exercices rapides avec retour immédiat'), b('A few minutes a day', 'Quelques minutes par jour'), [b('Vocabulary, grammar and phrase practice', 'Entraînement au vocabulaire, à la grammaire et aux expressions'), b('Instant explanations for every answer', 'Explications immédiates pour chaque réponse'), b('Works on phone, tablet or computer', 'Fonctionne sur téléphone, tablette ou ordinateur')], b('Build a daily habit in minutes.', 'Prendre une habitude quotidienne en quelques minutes.')),
        m(b('Windsor, the AI tutor', 'Windsor, le tuteur IA'), b('Any hour', 'À toute heure'), [b('Ask questions about vocabulary, emails and presentations', 'Poser des questions sur le vocabulaire, les e-mails et les présentations'), b('Sector-specific suggestions', 'Suggestions propres à votre secteur'), b('Read our Windsor AI policy for how it works', 'Consultez notre politique IA de Windsor pour savoir comment il fonctionne')], b('Get help the moment you need it.', 'Obtenir de l’aide au moment où vous en avez besoin.')),
        m(b('Progress tracking', 'Suivi de progression'), b('Every month', 'Chaque mois'), [b('A snapshot against your CEFR target', 'Un instantané par rapport à votre objectif CECRL'), b('Streaks, scores and areas to improve', 'Séries, scores et axes d’amélioration'), b('Team view for sponsors on corporate programmes', 'Vue d’équipe pour les sponsors des programmes entreprises')], b('See your progress, not just feel it.', 'Voir votre progression, pas seulement la ressentir.'))
      ],
      assess: b('Short checks inside the paths and a monthly progress snapshot against your CEFR target.', 'De courts contrôles dans les parcours et un point de progression mensuel par rapport à votre objectif CECRL.'),
      prereq: b('None. It is included with every Windsor programme.', 'Aucun. Il est inclus avec chaque programme Windsor.'),
      schedule: b('Use it any time on any device. In the current version your practice profile is stored in your browser.', 'Utilisez-le à tout moment sur n’importe quel appareil. Dans la version actuelle, votre profil de pratique est enregistré dans votre navigateur.'),
      sample: { title: b('A five-minute daily practice', 'Une pratique quotidienne de cinq minutes'), steps: [
        b('Open your path and see today’s three exercises.', 'Ouvrez votre parcours et voyez les trois exercices du jour.'),
        b('Complete a prepositions drill: “The report is due ___ Friday.”', 'Faites un exercice sur les prépositions : « The report is due ___ Friday. »'),
        b('Read the instant explanation: days take “on”.', 'Lisez l’explication immédiate : les jours prennent « on ».'),
        b('Ask Windsor to improve a sentence from your own work.', 'Demandez à Windsor d’améliorer une phrase de votre propre travail.'),
        b('Check your streak and tomorrow’s goal.', 'Consultez votre série et l’objectif de demain.')] },
      faq: [
        q(b('Is the LMS an extra cost?', 'Le LMS est-il payant en plus ?'), b('No. It is included in every programme.', 'Non. Il est inclus dans chaque programme.')),
        q(b('Does it work on my phone?', 'Fonctionne-t-il sur mon téléphone ?'), b('Yes. It works on phones, tablets and computers.', 'Oui. Il fonctionne sur téléphone, tablette et ordinateur.')),
        q(b('How does Windsor use my data?', 'Comment Windsor utilise-t-il mes données ?'), b('Please read our Windsor AI policy and privacy policy in the footer for the details.', 'Consultez notre politique IA de Windsor et notre politique de confidentialité en bas de page pour les détails.'))
      ]
    },

    interview: {
      syllabus: [
        m(b('Interview 1: baseline', 'Entretien 1 : référence'), b('Recorded', 'Enregistré'), [b('A realistic interview for your target role', 'Un entretien réaliste pour le poste visé'), b('Recorded on video with your agreement', 'Enregistré en vidéo avec votre accord'), b('Common questions: tell me about yourself, strengths, weaknesses', 'Questions classiques : parlez-moi de vous, forces, faiblesses')], b('See how you really come across.', 'Voir l’impression que vous donnez vraiment.')),
        m(b('Video review and expert feedback', 'Revue vidéo et retour d’un expert'), b('After each interview', 'Après chaque entretien'), [b('Watch yourself with your coach', 'Vous regarder avec votre coach'), b('Language, structure, body language and pace', 'Langue, structure, langage corporel et rythme'), b('Three priorities to fix before the next round', 'Trois priorités à corriger avant le tour suivant')], b('Know exactly what to change.', 'Savoir précisément quoi changer.')),
        m(b('Interview 2: behavioural questions', 'Entretien 2 : questions comportementales'), b('Recorded', 'Enregistré'), [b('“Tell me about a time when…” answered with PREP', '« Tell me about a time when… » avec la méthode PREP'), b('Describing achievements with numbers', 'Décrire des réalisations avec des chiffres'), b('Handling a question you did not expect', 'Gérer une question inattendue')], b('Give structured, convincing examples.', 'Donner des exemples structurés et convaincants.')),
        m(b('Interview 3: the final simulation', 'Entretien 3 : la simulation finale'), b('Recorded', 'Enregistré'), [b('A full interview with a panel-style mix of questions', 'Un entretien complet avec un mélange de questions de type jury'), b('Your own questions for the employer', 'Vos propres questions pour l’employeur'), b('Closing strongly and following up', 'Conclure avec force et relancer après l’entretien')], b('Walk into the real interview prepared.', 'Aborder le vrai entretien préparé.')),
        m(b('Written improvement report', 'Rapport écrit d’amélioration'), b('At the end', 'À la fin'), [b('Before and after comparison', 'Comparaison avant et après'), b('A phrase bank for your key answers', 'Une banque d’expressions pour vos réponses clés'), b('A short plan for the days before your interview', 'Un court plan pour les jours précédant votre entretien')], b('Leave with a clear record of what works.', 'Repartir avec une trace claire de ce qui fonctionne.'))
      ],
      assess: b('Each interview is reviewed on video with expert comments, and the written report compares your first and last interviews.', 'Chaque entretien est revu en vidéo avec les commentaires d’un expert, et le rapport écrit compare votre premier et votre dernier entretien.'),
      prereq: b('A working level of English and a target role or employer in mind.', 'Un niveau de travail en anglais et un poste ou un employeur visé.'),
      schedule: b('Three simulated interviews booked at times that suit you, in Abidjan or online. Recording is part of this service and is agreed with you before we start.', 'Trois entretiens simulés fixés à des moments qui vous conviennent, à Abidjan ou en ligne. L’enregistrement fait partie de ce service et est convenu avec vous avant de commencer.'),
      sample: { title: b('Answer “Tell me about yourself” in 60 seconds', 'Répondre à « Tell me about yourself » en 60 secondes'), steps: [
        b('Present: “I am a finance analyst with five years of experience in banking.”', 'Présent : « I am a finance analyst with five years of experience in banking. »'),
        b('Past: “Most recently I led the monthly reporting for a team of eight.”', 'Passé : « Most recently I led the monthly reporting for a team of eight. »'),
        b('Future: “I am now looking for a role where I can work with international clients.”', 'Futur : « I am now looking for a role where I can work with international clients. »'),
        b('Record it, watch it, and cut anything that does not help you get the job.', 'Enregistrez-vous, regardez-vous et supprimez tout ce qui ne vous aide pas à obtenir le poste.')] },
      faq: [
        q(b('Who sees my video?', 'Qui voit ma vidéo ?'), b('You and your coach. Recording is agreed with you beforehand, and you can ask what happens to it.', 'Vous et votre coach. L’enregistrement est convenu avec vous au préalable, et vous pouvez demander ce qu’il devient.')),
        q(b('Can you practise for my specific job?', 'Pouvez-vous préparer mon poste précis ?'), b('Yes. Tell us the role and employer, and the questions are tailored.', 'Oui. Indiquez-nous le poste et l’employeur, et les questions sont adaptées.')),
        q(b('Do you guarantee a job?', 'Garantissez-vous un emploi ?'), b('No. We improve how you present yourself in English, and the result depends on you and the employer.', 'Non. Nous améliorons votre façon de vous présenter en anglais, et le résultat dépend de vous et de l’employeur.'))
      ]
    },

    club: {
      syllabus: [
        m(b('Two live webinars a month', 'Deux webinaires en direct par mois'), b('Twice a month', 'Deux fois par mois'), [b('A business topic each time, with time for your questions', 'Un thème professionnel à chaque fois, avec du temps pour vos questions'), b('Example topics: negotiation phrases, clear status updates, meeting language', 'Exemples de thèmes : expressions de négociation, points d’étape clairs, langage de réunion'), b('Short practice tasks you can try the same week', 'De courts exercices à essayer la même semaine')], b('Keep speaking and learning every month.', 'Continuer à parler et à apprendre chaque mois.')),
        m(b('Members’ WhatsApp group', 'Groupe WhatsApp des membres'), b('Every day', 'Chaque jour'), [b('Ask quick questions about wording and grammar', 'Poser de rapides questions sur la formulation et la grammaire'), b('Share wins and useful phrases', 'Partager vos réussites et des expressions utiles'), b('Hear about events first', 'Être informé des événements en premier')], b('Stay connected to a community of professionals.', 'Rester en lien avec une communauté de professionnels.')),
        m(b('Windsor Dispatch newsletter', 'Newsletter Windsor Dispatch'), b('Every month', 'Chaque mois'), [b('Practical tips you can use in your next email or meeting', 'Conseils pratiques pour votre prochain e-mail ou votre prochaine réunion'), b('Vocabulary from the Daily Business English brief', 'Vocabulaire issu du point Business English du jour'), b('News about programmes and events', 'Nouvelles des programmes et des événements')], b('Never lose touch with your English.', 'Ne jamais perdre le fil de votre anglais.'))
      ],
      assess: b('The Club is about practice and community, so there are no exams. Your coaches can recommend a refresher programme if you want a measured check of your level.', 'Le Club est axé sur la pratique et la communauté : il n’y a pas d’examens. Vos coachs peuvent recommander un programme de remise à niveau si vous souhaitez un contrôle mesuré de votre niveau.'),
      prereq: b('Open to Windsor alumni.', 'Ouvert aux anciens apprenants Windsor.'),
      schedule: b('Monthly membership. Webinar dates are shared in the members’ group and in our Events section.', 'Abonnement mensuel. Les dates des webinaires sont partagées dans le groupe des membres et dans notre section Événements.'),
      sample: { title: b('A typical webinar', 'Un webinaire type'), steps: [
        b('A ten-minute introduction to the topic, for example giving bad news politely.', 'Dix minutes d’introduction au thème, par exemple annoncer une mauvaise nouvelle avec tact.'),
        b('Key phrases on screen, with examples from real workplaces.', 'Expressions clés à l’écran, avec des exemples tirés de vrais lieux de travail.'),
        b('A short breakout practice with a partner.', 'Un court exercice à deux.'),
        b('Open questions from members.', 'Questions ouvertes des membres.'),
        b('One challenge to try at work this week.', 'Un défi à tenter au travail cette semaine.')] },
      faq: [
        q(b('Who can join the Club?', 'Qui peut rejoindre le Club ?'), b('Past Windsor learners. Ask us if you are not sure whether you qualify.', 'Les anciens apprenants Windsor. Demandez-nous si vous n’êtes pas sûr d’être éligible.')),
        q(b('How does billing work?', 'Comment fonctionne la facturation ?'), b('It is a monthly membership, quoted on request. See our enrolment and refunds terms for the rules.', 'C’est un abonnement mensuel, sur devis. Consultez nos conditions d’inscription et de remboursement pour les règles.')),
        q(b('What if I miss a webinar?', 'Et si je manque un webinaire ?'), b('Ask in the members’ group and we will point you to the key material.', 'Demandez dans le groupe des membres et nous vous orienterons vers les supports clés.'))
      ]
    }
  };

  window.WBE_DATA.PROGRAMMES.forEach(function (p) {
    var s = S[p.id]; if (!s) return;
    Object.keys(s).forEach(function (k) { p[k] = s[k]; });
  });
})();
